apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app  # Matches the label in the Deployment
  ports:
  - protocol: TCP
    port: 80        # Expose the Flask app on port 80
    targetPort: 5000 # Maps to the container's port
  type: NodePort      # Expose the service on a random port of the node
